image: gitpod/workspace-node

tasks:
  - init: |
      npm install -g @expo/cli eas-cli
      npm install
    command: |
      echo "Ready to build F1 Barcode Scanner!"
      echo "Run: eas build -p android --profile preview"

ports:
  - port: 19000
    onOpen: ignore
  - port: 19001  
    onOpen: ignore
  - port: 19002
    onOpen: ignore

vscode:
  extensions:
    - ms-vscode.vscode-typescript-next
    - esbenp.prettier-vscode
