workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 18.19.0
      java: 17
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.yourcompany.f1barcodescanner"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Set up Android project
        script: |
          npx expo prebuild -p android --clean
      
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true