[build]
  command = "npm ci --legacy-peer-deps && npx expo export --platform web --output-dir dist && cp public/_redirects dist/_redirects 2>/dev/null || true"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(*), microphone=(*)"